version: '3'
services:

  my-app
    image: bagrat92/nodejs-project:$1
    ports:
      - 3000:3000
    # networks:
    #   - mongo-db


  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db-data:/data/db
    # networks:
    #   - mongo-db


  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    # networks:
    #   - mongo-db
      
volumes:
  db-data:
    driver: local

# networks:
#   mongo-db:
#     driver: bridge
