apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: k8s-web
        image: bagrat92/myapp:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-pod-service
  labels:
    env  : production
    owner: app
spec:
  selector:
    app: app
  ports:
  - name: app-listener
    protocol: TCP
    targetPort: 3000
    port: 80
  type: LoadBalancer
