apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=       # Enter Your_USERNAME Encoding  base64
  mongo-root-password: UGEkJHcwOGQ=   # Enter YOOR_PASSWORD Encoding  base64
